set_property PACKAGE_PIN P5 [get_ports {inputs[0]}]
set_property PACKAGE_PIN P4 [get_ports {inputs[1]}]
set_property PACKAGE_PIN P3 [get_ports {inputs[2]}]
set_property PACKAGE_PIN P2 [get_ports {inputs[3]}]
set_property PACKAGE_PIN R2 [get_ports {inputs[4]}]
set_property PACKAGE_PIN M4 [get_ports {inputs[5]}]
set_property PACKAGE_PIN N4 [get_ports {inputs[6]}]
set_property PACKAGE_PIN R1 [get_ports {inputs[7]}]
set_property PACKAGE_PIN F6 [get_ports {light[0]}]
set_property PACKAGE_PIN G4 [get_ports {light[1]}]
set_property PACKAGE_PIN G3 [get_ports {light[2]}]
set_property PACKAGE_PIN J4 [get_ports {light[3]}]
set_property PACKAGE_PIN H4 [get_ports {light[4]}]
set_property PACKAGE_PIN J3 [get_ports {light[5]}]
set_property PACKAGE_PIN J2 [get_ports {light[6]}]
set_property PACKAGE_PIN K2 [get_ports {light[7]}]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports *]

set_property PACKAGE_PIN T1 [get_ports zero]
set_property PACKAGE_PIN H17 [get_ports speaker]

set_property PACKAGE_PIN V1 [get_ports low_button]
set_property PACKAGE_PIN R11 [get_ports high_button]

set_property PACKAGE_PIN U4 [get_ports mode_switch]
set_property PACKAGE_PIN P15 [get_ports rst]
set_property PACKAGE_PIN K1 [get_ports {mode_light[0]}]
set_property PACKAGE_PIN H6 [get_ports {mode_light[1]}]
set_property PACKAGE_PIN H5 [get_ports {mode_light[2]}]


set_property PACKAGE_PIN M1 [get_ports low_light]
set_property PACKAGE_PIN K3 [get_ports high_light]

set_property PACKAGE_PIN G2 [get_ports tub_sel]

set_property PACKAGE_PIN D5 [get_ports {display_segments[0]}]
set_property PACKAGE_PIN B2 [get_ports {display_segments[1]}]
set_property PACKAGE_PIN B3 [get_ports {display_segments[2]}]
set_property PACKAGE_PIN A1 [get_ports {display_segments[3]}]
set_property PACKAGE_PIN B1 [get_ports {display_segments[4]}]
set_property PACKAGE_PIN A3 [get_ports {display_segments[5]}]
set_property PACKAGE_PIN A4 [get_ports {display_segments[6]}]
set_property PACKAGE_PIN B4 [get_ports {display_segments[7]}]

set_property PACKAGE_PIN R17 [get_ports song_switch]
